@url=http://localhost:8888/api/v1/permissions

### CREATE
POST {{url}}
Content-Type: application/json

{
  "name": "Post View",
  "desc": "Xem bài viết",
  "alias": "post.view"
}

### Update
PATCH {{url}}/649e5327c87767850e8ef701
Content-Type: application/json

{
  "name": "Product add",
  "desc": "Thêm sản phẩm",
  "alias": "product.add"
}

### GET
GET {{url}}

### GET ID
GET {{url}}/649e5327c87767850e8ef701